call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-sensible'
Plug 'junegunn/vim-easy-align'
Plug 'myusuf3/numbers.vim'
Plug 'bling/vim-airline'
Plug 'terryma/vim-multiple-cursors'
" Theme
Plug 'altercation/vim-colors-solarized'

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'kien/ctrlp.vim', { 'on': 'CtrlP' }
Plug 'fatih/vim-go', { 'for':  'go' }
Plug 'ElmCast/elm-vim', { 'for':  'elm' }
Plug 'nsf/gocode', { 'for': 'go', 'rtp': 'vim', 'do': '~/.vim/plugged/gocode/vim/symlink.sh' }
Plug 'tpope/vim-fireplace', { 'for':  ['clj', 'cljs', 'edn'] }
Plug 'tell-k/vim-autopep8', { 'for': 'python' }

" Erlang specific
Plug 'vim-erlang/vim-erlang-runtime', { 'for': ['erl', 'hrl'] }
Plug 'vim-erlang/erlang-motions.vim', { 'for': ['erl', 'hrl'] }
Plug 'vim-erlang/vim-erlang-omnicomplete'
Plug 'vim-erlang/vim-erlang-tags'

Plug 'scrooloose/syntastic'
Plug 'SirVer/ultisnips'
"" Show a VCS diff using Vim's sign column.
Plug 'mhinz/vim-signify'
" Unload/delete/wipe a buffer, keep its window(s), display last accessed buffer(s)
Plug 'vim-scripts/bufkill.vim'

" Before on OSX
" install ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
" install brew install caskroom/cask/brew-cask
" install brew install macvim --override-system-vim
" Plug 'Valloric/YouCompleteMe', { 'do': 'git submodule update --init --recursive && ./install.sh --gocode-completer', 'for': ['go'] }
Plug 'Valloric/YouCompleteMe', { 'do': 'git submodule update --init --recursive && ./install.py --clang-completer --gocode-completer' }
autocmd! User YouCompleteMe call youcompleteme#Enable()

Plug 'tomtom/tcomment_vim'

call plug#end()

set nocompatible               " be iMproved
filetype off                   " required!

" Remove all unwanted whitespaces on save
autocmd BufWritePre * :%s/\r\+$//e " Windows newlines
autocmd BufWritePre * :%s/\s\+$//e
" Turn off search highlight
nnoremap <leader><space> :nohlsearch<CR>

" Appearance
syntax on
set background=dark
let g:solarized_termcolors=256
color solarized

" set clipboard=unnamedplus " Clipboad as default set to +
set cursorline " Higlight current line
set hidden " When set allow switch between buffers even when buffer have change
set autoindent " Indent the next line similiar to current line
set smartindent " Be smart with indent
set copyindent " Use same indentation characters as current line
set expandtab " Use spaces instead of tabs for indentation
set shiftwidth=4 " Use 4 spaces for indentation
set shiftround  " Round all indentations to multiple of shiftwidth
set tabstop=4   " Set tabs to be equivalent to 4 spaces (fixes retab)
set number      " Set line number
set autoread    " Set to auto read when a file is changed from the outside
set backspace=indent,eol,start " Free the backspace and enable arrow keys and h l to move past the beginning and end of lines
set whichwrap+=<,>,h,l
set showmatch   " Show matching bracets when text indicator is over them
set nowb        " Turn backup off "set nobackup
set noswapfile
set incsearch   " Search before hit enter
set hlsearch    " Highlight search results
set wildmenu    " Show available commands in list
set lazyredraw  " redraw only when we need to.

" Persistent undo
if version >= 703
    let ud=$HOME . "/.vimundo"

    if !isdirectory(ud)
        call mkdir(ud)
        echo "Created undo directory: " . ud
    endif

    execute "set undodir=" . ud
    set undofile
endif
set undolevels=1000

" Navigation
map } :bnext<CR>
map { :bprevious<CR>
map L :bnext<CR>
map H :bprevious<CR>
nmap mj :m+1<CR>
nmap mk :m-2<CR>
map <leader>p :NERDTreeToggle<CR>
map <c-p> :CtrlP<CR>
map <leader>/ :TComment<CR>
map <leader>? :TCommentInline<CR>

augroup configgroup
    autocmd!
    autocmd VimEnter * highlight clear SignColumn
    autocmd BufEnter *.zsh-theme setlocal filetype=zsh
    autocmd BufEnter *.js,*.json,*.yml setlocal tabstop=2
    autocmd BufEnter *.js,*.json,*.yml setlocal shiftwidth=2
    autocmd BufEnter *.js,*.json,*.yml setlocal softtabstop=2
augroup END

" vim-airline
let g:airline#extensions#tabline#enabled = 1
"" let g:airline_powerline_fonts = 1
set laststatus=2

" syntastic
let g:syntastic_always_populate_loc_list=1
let g:syntastic_python_checkers = ['flake8']

"" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = "<C-o>"

" vim-multiple-cursors
" Default mapping
let g:multi_cursor_next_key='<C-n>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_skip_key='<C-x>'
let g:multi_cursor_quit_key='<Esc>'
let g:multi_cursor_exit_from_insert_mode=0

"" BufKill
"map <leader>q :bd<CR>
"map <leader>Q :bd!<CR>

"" tern
"autocmd FileType javascript map <Leader>d :TernDef<CR>

"" tidy content
"autocmd Syntax xml nmap <leader>t :.,%!xmllint --format --recover -<CR>

" let g:numbers_exclude = ['unite', 'tagbar', 'startify', 'gundo', 'vimshell', 'w3m', 'goyo']

" fatih/vim-go
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_structs = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_def_mapping_enabled = 0

" YCM improvements http://vim.wikia.com/wiki/Make_Vim_completion_popup_menu_work_just_like_in_an_IDE
set completeopt=longest,menuone
" nter key will simply select the highlighted menu item, just as <C-Y> does.
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
" open omni completion menu closing previous if open and opening new menu without changing the text
inoremap <expr> <C-Space> (pumvisible() ? (col('.') > 1 ? '<Esc>i<Right>' : '<Esc>i') : '') .
            \ '<C-x><C-o><C-r>=pumvisible() ? "\<lt>C-n>\<lt>C-p>\<lt>Down>" : ""<CR>'
" open user completion menu closing previous if open and opening new menu without changing the text
inoremap <expr> <S-Space> (pumvisible() ? (col('.') > 1 ? '<Esc>i<Right>' : '<Esc>i') : '') .
            \ '<C-x><C-u><C-r>=pumvisible() ? "\<lt>C-n>\<lt>C-p>\<lt>Down>" : ""<CR>'

let g:ycm_key_list_select_completion = ['<TAB>', '<Down>']

nnoremap <leader>jd :YcmCompleter GoTo<CR>

" vim-erlang/vim-erlang-tags
let g:erlang_tags_ignore = ['.eunit']
